---
addons:
  apt:
    packages:
    - zsh
sudo: required
dist: trusty
services: docker

before_install:
  - docker pull pamplemousse/ansible
  - docker pull pamplemousse/latex
  - docker pull pamplemousse/nodejs
  - docker pull pamplemousse/python
  - docker pull pamplemousse/ruby

install:
  - export WORKSPACE=$HOME/Workspace
  - export TOOLS=$HOME/Workspace/tools
  - mkdir $WORKSPACE && mkdir $TOOLS
  - git clone --depth 1 https://github.com/ko1nksm/shellspec.git
  - git clone --depth 1 https://github.com/ansible/ansible.git $TOOLS/ansible
  - cd $TOOLS/ansible && git fetch --tags && git checkout v2.5.0 && cd -
  - git clone https://github.com/Pamplemousse/audit-ssh-client-config.git $TOOLS/audit-ssh-client-config

env:
  - SSH_AUTH_SOCK: /tmp/ssh-whatever/agent.4242

script:
  - shellspec/shellspec --shell zsh
